### PR TITLE
Create `package.json` to prepare for npm release

### PR DESCRIPTION
**Pull request by astorije**
This file was created by following steps listed at thelounge.github.io/docs/plugins/themes.html.

After publishing it on npm, it will be available with all other themes https://www.npmjs.com/search?q=keywords%3Athelounge-theme

It can then be installed on The Lounge (as of [v2.5.0](https://github.com/thelounge/lounge/releases/tag/v2.5.0)) using the `lounge install` (prior to v2.7.0) or `thelounge install` (v2.7.0 and up) command.

### CODE REVIEW

**Comment by astorije** [comment]
Hey @bews, one last nudge, just in case you stop by? :)

**Comment by bews** [comment]
@astorije Sorry, I didn't notice this PR at all ;(

NP, I can merge this, but not sure if it still works well with the latest version.

**Comment by astorije** [comment]
Hey @bews, thanks for your reply! I would just go ahead with this, deploy to npm so it appears in the list (which we'll link to directly from the navbar of the new docs), and if it needs tweaking, I'm sure whoever ends up using it will help fixing it :)

**Comment by bews** [comment]
NP, merged.
But it looks like I have some problems with my npm account and can't publish it atm. Time to check how npm support works :)

**Pull request merged**
